development:
  adapter: postgresql
  encoding: unicode
  host: ec2-34-252-42-55.eu-west-1.compute.amazonaws.com
  database: d96rjper8bpega
  pool: 2
  username: u7i2s438ef2r8a
  password: pe220f537ebda4ef5f32c0ceb77dda698da3b0a2d45986288f8fb64a88daab89e

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  # host: <%= ENV['DATABASE_HOST'] %>
  # database: <%= ENV['DATABASE_NAME'] %>
  # username: <%= ENV['DATABASE_USER'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>