development:
  adapter: postgresql
  encoding: unicode
  host: ec2-54-247-125-137.eu-west-1.compute.amazonaws.com
  database: dj9k78es1flcq
  pool: 2
  username: mlltcqhopccwox
  password: 8d78af787126b27fddf6b74daa52d761cfba46e278386ab77ac050b82c58b8b1

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  # host: <%= ENV['DATABASE_HOST'] %>
  # database: <%= ENV['DATABASE_NAME'] %>
  # username: <%= ENV['DATABASE_USER'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>